name: CD (prod)

on:
  push:
    branches: [ "prod" ]

env:
  IMAGE: ${{ secrets.DOCKER_IMAGE }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest mypy pylint
          pytest -q || true
          mypy . || true
          set +e; pylint $(git ls-files '*.py') || true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy on Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key:      ${{ secrets.DO_SSH_PRIVATE_KEY }}
          port:     ${{ secrets.DO_SSH_PORT || 22 }}
          script_stop: true
          script: |
            set -e
            docker pull ${{ env.IMAGE }}:latest
            docker rm -f sayhi || true
            docker run --name sayhi --rm \
              -v /opt/assignment_outputs:/app/data \
              ${{ env.IMAGE }}:latest
            ls -lh /opt/assignment_outputs | tail -n +1
